import random
words = [
    'AUTOCRACY', 'EMANCIPATION', 'GIRAFFE', 'WINDOW', 'UBUNTU', 'STARGAZING', 'TAKE', 'FORWARD', 'PROGRESS',
    'STRUGGLE', 'CELL', 'HAPPINESS', 'GRACE', 'PEACE', 'PROSPERITY', 'DOG', 'RIGHT', 'LEARN', 'HEALTH',
    'OFTEN', 'ENERGY', 'FILESYSTEM', 'PROCESSOR', 'PYTHON', 'KINDNESS', 'JAVA', 'SPRING', 'SUMMER', 'DECISION',
    'DEDICATED', 'UPWARDS', 'OBJECT', 'HIGH', 'FLYING', 'FIX', 'FACE', 'SMILE', 'LAUGHTER', 'KNOWLEDGE',
    'POTATO', 'PHOTO', 'WINE', 'SWEET', 'BEER', 'VACATION', 'TRAVELLING', 'DISCOVERY', 'HEUREKA', 'CHAOS',
    'CREATIVITY', 'FRIENDSHIP', 'LOVE', 'MONEY', 'HEAVEN', 'NIRVANA', 'STAIRWAY', 'APPLE', 'SAND', 'SPACE',
    'FREEDOM', 'CLEAN', 'WARM', 'MEAL', 'CAMPFIRE', 'BBQ', 'BEE', 'HONEY', 'SUNLIGHT', 'SNOW', 'ICE', 'SPORT',
    'AUSTRALIA', 'LIGHT', 'INFORMATION', 'INTELLIGENCE', 'GROWING', 'LEVELUP', 'ADORE', 'SKY', 'LIMIT', 'DREAM'
]

def getRandomWord():
    return words[random.randint(0, len(words) - 1)]