def printStartingAnimation():
    print('      /:""|')
    print('     |: 66|_,')
    print('     C     _)')
    print('      \ .o|       Man I forgot my lunch at home! ')
    print('       ) / ')
    print('      /`\\')
    print('     || |Y|')
    print('     || |#|')
    print('     || |#|')
    print('     || |#|')
    print('     :| |=:')
    print('     ||_|,|')
    print('     \)))||')
    print('  |~~~`-`~~~|')
    print('  |         |')
    print('  |_________|')
    print('  |_________|')
    print('      | ||')
    print('      |_||')
    print('      (____))')